namespace CourseSelectionApp.Readers.NodeFormats
{
    public enum CourseNode
    {
        Id,
        Name,
        Stage,
        Credits,
        Hours,
        RequiredOrElectiveCourse,
        Teacher,
        Sunday,
        Monday,
        Tuesday,
        Wednesday,
        Thursday,
        Friday,
        Saturday,
        ClassRoom,
        NumberOfStudents,
        NumberOfDropStudents,
        TeachingAssistant,
        Language,
        Syllabus,
        Note,
        Audit,
        Experiment
    }
}
